using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalNotes.Models
{

    [Table("notes")] // Create notes table in Database
    public partial class Notes
    {
        // Create Column for ID(AutoGenerated) in "notes" table
        [Key]
        [Column("ID", TypeName = "int(10)")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // Create Column for Description in "notes" table
        [Required]
        [Column("Note",TypeName = "varchar(255)")]
        public string Description { get; set; }

        // Create Column for Date in "notes" table
        [Required]
        [Column("date",TypeName = "Date")]
        public DateTime Date { get; set; }

        // Create Column for UserId(ForeignKey)  in "notes" table
        [Column("UserId", TypeName = "int(10)")]
        public int UserId { get; set; }

        // InverseProperty for Foreign Key 
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Models.User.Notes))]
        public virtual User Users { get; set; }
    }
}
