using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace PersonalNotes.Models
{
    [Table("user")]//Create user table in Database
    public partial class User
    {

        public User()
        {
            Notes = new HashSet<Notes>();
        }

        // Create Column for ID(AutoGenerated) in "user" table
        [Key]
        [Column("ID", TypeName = "int(10)")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // Create Column for FirstName in "user" table
        [Required]
        [Column("fname", TypeName = "varchar(50)")]
        public string FirstName { get; set; }

        // Create Column for LastName in "user" table
        [Required]
        [Column("lname", TypeName = "varchar(50)")]
        public string LastName { get; set; }

        // Create Column for Email in "user" table
        [Required]
        [Column("email", TypeName = "varchar(50)")]
        public string Email { get; set; }

        //Create Column for Paassword in "user" table
        [Required]
        [Column("password", TypeName = "varchar(50)")]
        public string Password { get; set; }

        // InverseProperty for Foreign Key 
        [InverseProperty(nameof(Models.Notes.Users))]
        public virtual ICollection<Notes> Notes { get; set; }

    }

}
